### PR TITLE
DD-526 create url for custom terms

### PR DESCRIPTION
**Pull request by mderuijter**
Create a dataset with a custom license

Enter the custom license url into your browser (replace brackets, example version OR draft syntax provided):
```
https://dar.dans.knaw.nl/api/datasets/:persistentId/versions/{1.0|:draft}/customlicense?persistentId={doi:10.5072/DAR/BXBIEB}
```
Should result in a redirect to dataset's termsTab

### CODE REVIEW

**Comment by janvanmansum** [comment]
@mderuijter The license URL should be publicly available, but currently I need to send my API token when accessing it via curl:
```
curl -v -k 'https://dar.dans.knaw.nl/api/datasets/:persistentId/versions/1.0/customlicense?persistentId=doi:10.5072/DAR/VKCWQ8'
...
< HTTP/1.1 401 Unauthorized
< Date: Thu, 08 Jul 2021 09:43:56 GMT
< Server: Apache/2.4.37 (centos) OpenSSL/1.1.1g
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: PUT, GET, POST, DELETE, OPTIONS
< Access-Control-Allow-Headers: Accept, Content-Type, X-Dataverse-Key
< Set-Cookie: JSESSIONID=5809c8332ea3b13779cf0a871256; Path=/; Secure; HttpOnly
< Content-Type: application/json;charset=UTF-8
< Content-Length: 117
```

I am not sure it makes sense that the terms of a draft dataset also have a persistent URI.  @qqmyers, any thoughts on this?

**Comment by janvanmansum** [comment]
@mderuijter : found another bug: if there is no custom license, the redirect is still happening. Review specs in issue.

**Comment by mderuijter** [comment]
> @mderuijter : found another bug: if there is no custom license, the redirect is still happening. Review specs in issue.

On it, overlooked that.

**Comment by qqmyers** [comment]
I don't think we need to have a URI when it's in draft, but just redirecting to the access-controlled draft dataset page/terms tab is probably OK too if that's easier.

**Comment by janvanmansum** [comment]
I agree, and that is what is currently happening.

**Pull request merged**
