### PR TITLE
Jira ddn 314

### PR DESCRIPTION
**Pull request by ekoi**
# RFI Checklist

_**Before** submitting the pull request, fill out sections (1.) Related Issues and (2.) Pull Request Checklist._

### 1. Related Issues

_List and [link](https://guides.github.com/features/issues/#notifications) to the issues in this Pull Request._

- [#### + Title HERE]

---
### 2. Pull Request Checklist

- [ ]  Functionality completed as described in FRD
- [ ]  Dependencies, risks, assumptions in FRD addressed
- [ ]  Unit tests completed
- [ ]  Deployment requirements identified (e.g., SQL scripts, indexing)
- [ ]  Documentation completed
- [ ]  All code checkins completed

---
### 3. Review Checklist

_**After** the pull request has been submitted, fill out this section._

- [ ]  Code review completed or waived
- [ ]  Testing requirements completed
- [ ]  Usability testing completed or waived
- [ ]  Support testing completed or waived
- [ ]  Merged with develop branch and resolved conflicts

### CODE REVIEW

**Comment by PaulBoon** [comment]
I am a bit puzzled by this PR. 
The only hint I get is the title referring to the Jira issue 314 (nice number ;-) BTW)
And that is adding an API for moving datasets to other verses?
Why then do I get a PR with 1008 commits and 468 files changes, I cannot seriously review this.

**Comment by 4tikhonov** [comment]
Please ignore it, Eko pulled his stuff in the wrong branch (develop).

**Comment by PaulBoon** [comment]
Ok, I see that it was merged: https://github.com/DANS-KNAW/dataverse/pull/9/files

**Comment by PaulBoon** [comment]
Already merged in other PR

**Pull request closed without merging**
